### ISSUE TITLE
List with more than 5000 records

### ISSUE THREAD

**Issue by rbouillon** [inclinetechnical/QuickCAML#6]
When executing a query on a list that contains more than 5000 records, I get the following error:

Internal Server Error. Exception of type 'Microsoft.SharePoint.SoapServer.SoapServerException' was thrown. The attempted operation is prohibited because it exceeds the list view threshold enforced by the administrator. 

The query that I ran is the following:

<View>
    <Query>
        <Where>
            <Eq>
                <FieldRef Name="Title" />
                <Value Type="Text">E03dlm7.001</Value>
            </Eq>
        </Where>
    </Query>
    <ViewFields>
    </ViewFields>
</View>

Is this normal behavior although my row limit is set to 10?

**Comment by inclinetechnical** [comment]
Yes, unfortunately that's normal in SharePoint 2010 and 2013 and not a problem with QuickCAML.

Setting a row limit often isn't enough to solve that error because a behind-the-scenes sort operation and other things in the back-end database that you have no control over can trigger it too - not just the number of rows you ask for.

There's no single solution to dealing with list view threshold exceptions. The answer is usually a combination of:

1) Possibly rewriting parts of your query to avoid the back-end sort/filter operation that's triggering the error. For example, the "OrderBy" tag has special attributes you can use to specify that indexed columns are always used for sorting. See http://bit.ly/1PhqZNF.

2) Changing which columns in the list are indexed. Sometimes non-indexed columns in a query will trigger that error.

3) As a last resort, you can bump up (or disable) the thresholds on the lists or in Central Administration (globally). That approach isn't recommended by Microsoft, though, and often isn't necessary. In 99% of cases where I've seen that error, #1 and/or #2 was enough to fix it. I've worked on projects where developers were lazy and simply bumped up the threshold in Central Admin, and it almost always causes problems later.

If you do a Google search for "sharepoint caml query list view threshold," you'll see a lot of articles and blog posts talking about that error and the various workarounds people use.

(Side note: The error you mentioned is actually one reason I wrote QuickCAML in the first place. I too have seen that error many times, and I wanted a quick way to test and edit my CAML queries so I could re-work them until I got rid of the error.)

**Comment by rbouillon** [comment]
Bart,
Thanks for getting back to me regarding this issue.

Rafael
